apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: ibougajd/postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
      # Use individual mapping for the password since it comes from a Secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transcendence-secrets
              key: DB_PASS
    # Use envFrom to pull in everything else (DB_USER, DB_NAME, etc.)
        envFrom:
          - configMapRef:
              name: transcendence-config
