apiVersion: v1
kind: ConfigMap
metadata:
  name: transcendence-config
  namespace: transcendence
data:
  HOST: "0.0.0.0"
  GATEWAY_PORT: "443"
  AUTH_SERVICE_PORT: "3004"
  CHAT_SERVICE_PORT: "3001"
  USER_SERVICE_PORT: "3002"
  FRONT_SERVICE_PORT: "3003"
  LISTINGS_SERVICE_PORT: "3005"
  AI_SERVICE_PORT: "3006"
  APP_URL: "https://localhost/"
  FRONTEND_URL: "http://localhost:3003/"
  DB_USER: "postgres"
  DB_NAME: "postgres"
  JWT_EXPIRES_IN: "7d"
  DATABASE_URL: "postgresql://postgres:12345678@database:5432/postgres?schema=public"
  ELASTIC_VERSION: "7.17.21"
  ELASTIC_SECURITY: "false"
  POSTGRES_PORT: "5432"
  INTRA42_CALLBACK_URL: "https://localhost/api/auth/42/callback"
  GOOGLE_CALLBACK_URL: "https://localhost/api/auth/google/callback"