# k8s/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: transcendence # This forces EVERYTHING to this namespace
secretGenerator:
- name: nginx-certs
  files:
    - transcendence.crt=certs/tls.crt
    - transcendence.key=certs/tls.key

resources:
  - namespace.yaml
  - configMap.yaml
  - secrets.yaml
  - nginx/gateway.deployment.yaml
  - nginx/gateway.service.yaml
  - frontend/front.deployment.yaml
  - frontend/front.service.yaml
  - backend/auth/auth.deployment.yaml
  - backend/auth/auth.service.yaml
  - backend/chat/chat.deployment.yaml
  - backend/chat/chat.service.yaml
  - backend/user/user.deployment.yaml
  - backend/user/user.service.yaml
  - backend/listings/listings.deployment.yaml
  - backend/listings/listings.service.yaml
  - backend/database/database.deployment.yaml
  - backend/database/database.service.yaml
  - backend/ai/ai.deployment.yaml
  - backend/ai/ai.service.yaml
  