apiVersion: v1
kind: Secret
metadata:
  name: transcendence-secrets
  namespace: transcendence
type: Opaque
stringData:
  GEMINI_API_KEY: "AIzaSyCpnfO4MZ-kq9r3eNWrgjqXmCznO2Xrj1s"
  DB_PASS: "12345678"
  JWT_SECRET: "zaba_w_chta_sabba_layn3ltbonmha_hayati"
  ELASTIC_PASSWORD: "ilyass"
  GF_ADMIN_PASSWORD: "admin"
  INTRA42_CLIENT_ID: "u-s4t2ud-daa3ad47f7cbba778275b16a21c5d1502218a1707ec8ad691fa63cef0caa007e"
  INTRA42_CLIENT_SECRET: "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"
  GOOGLE_CLIENT_ID: "142886815119-60nlktnb0utrb8a3vblggoeu7jhs422q.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"