apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings-deployment
  labels:
    app: listings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listings
  template:
    metadata:
      labels:
        app: listings
    spec:
      containers:
      - name: listings
        image: ibougajd/listings:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3005
        envFrom:
        - configMapRef:
            name: transcendence-config
        - secretRef:
            name: transcendence-secrets
