apiVersion: v1
kind: Service
metadata:
  name: listings
  labels:
    app: listings-service
spec:
  type: ClusterIP
  selector:
    app: listings
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
