apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: ibougajd/chat:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: transcendence-config
        - secretRef:
            name: transcendence-secrets
